name: pr-test

on:
  pull_request:
    branches:
      - 'master'

jobs:
  test:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [21, 24, 30]
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: decrypt debug files
        run: |
          echo ${{ secrets.DEBUG_GOOGLE_SERVICE_JSON }} | base64 -d > app/src/debug/google-services.json
          echo ${{ secrets.DEBUG_SIGNING_GRADLE }} | base64 -d > dependencies/signing.gradle
          sed -i '' '${{ secrets.DEBUG_SED_COMMAND }}' app/build.gradle

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Unit Test
        run: bash gradlew clean testDebugUnitTest

      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: UI Test
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          script: bash gradlew connectedCheck

      - name: Slack Notification
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,action,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}